import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, ScrollView, StyleSheet, ActivityIndicator, KeyboardAvoidingView, Platform } from 'react-native';

const GROQ_KEY = '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';

export default function App() {
  const [input, setInput] = useState('');
    const [chat, setChat] = useState([]);
      const [loading, setLoading] = useState(false);

        const askBB = async () => {
            if (!input.trim()) return;
                const userMsg = { role: 'user', text: input };
                    setChat(prev => [...prev, userMsg]);
                        setInput('');
                            setLoading(true);

                                try {
                                      const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
                                              method: 'POST',
                                                      headers: {
                                                                'Authorization': `Bearer ${GROQ_KEY}`,
                                                                          'Content-Type': 'application/json',
                                                                                  },
                                                                                          body: JSON.stringify({
                                                                                                    model: 'llama-3.1-8b-instant',
                                                                                                              messages: [
                                                                                                                          { role: 'system', content: 'Nuvvu BB AI. Bobby create chesadu. Physics doubts ki short ga, Telugu style lo answer ivvu bro.' },
                                                                                                                                     ...chat.map(m => ({ role: m.role, content: m.text })),
                                                                                                                                                 { role: 'user', content: input }
                                                                                                                                                           ],
                                                                                                                                                                     temperature: 0.7,
                                                                                                                                                                             }),
                                                                                                                                                                                   });
                                                                                                                                                                                         const data = await res.json();
                                                                                                                                                                                               const reply = data.choices?.[0]?.message?.content || 'Error ra bro';
                                                                                                                                                                                                     setChat(prev => [...prev, { role: 'assistant', text: reply }]);
                                                                                                                                                                                                         } catch (e) {
                                                                                                                                                                                                               setChat(prev => [...prev, { role: 'assistant', text: 'Network error bro. Net check chey.' }]);
                                                                                                                                                                                                                   }
                                                                                                                                                                                                                       setLoading(false);
                                                                                                                                                                                                                         };

                                                                                                                                                                                                                           return (
                                                                                                                                                                                                                               <KeyboardAvoidingView style={styles.bg} behavior={Platform.OS === 'ios'? 'padding' : 'height'}>
                                                                                                                                                                                                                                     <Text style={styles.title}>BB AI ⚡ Groq</Text>
                                                                                                                                                                                                                                           <ScrollView style={styles.chat}>
                                                                                                                                                                                                                                                   {chat.length === 0 && <Text style={styles.hint}>Bro nenu BB AI. Bobby create chesadu. Physics doubt adugu 🔥</Text>}
                                                                                                                                                                                                                                                           {chat.map((m, i) => (
                                                                                                                                                                                                                                                                     <View key={i} style={[styles.msg, m.role === 'user'? styles.user : styles.ai]}>
                                                                                                                                                                                                                                                                                 <Text style={styles.msgText}>{m.text}</Text>
                                                                                                                                                                                                                                                                                           </View>
                                                                                                                                                                                                                                                                                                   ))}
                                                                                                                                                                                                                                                                                                           {loading && <ActivityIndicator color="#FF6B00" style={{marginTop: 10}} />}
                                                                                                                                                                                                                                                                                                                 </ScrollView>
                                                                                                                                                                                                                                                                                                                       <View style={styles.inputRow}>
                                                                                                                                                                                                                                                                                                                               <TextInput
                                                                                                                                                                                                                                                                                                                                         style={styles.input}
                                                                                                                                                                                                                                                                                                                                                   placeholder="Physics doubt adugu bro..."
                                                                                                                                                                                                                                                                                                                                                             placeholderTextColor="#999"
                                                                                                                                                                                                                                                                                                                                                                       value={input}
                                                                                                                                                                                                                                                                                                                                                                                 onChangeText={setInput}
                                                                                                                                                                                                                                                                                                                                                                                           multiline
                                                                                                                                                                                                                                                                                                                                                                                                   />
                                                                                                                                                                                                                                                                                                                                                                                                           <TouchableOpacity style={styles.btn} onPress={askBB}>
                                                                                                                                                                                                                                                                                                                                                                                                                     <Text style={styles.btnText}>Send</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                             </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                   </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                       </KeyboardAvoidingView>
                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                         const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                           bg: { flex: 1, backgroundColor: '#000', paddingTop: 50 },
                                                                                                                                                                                                                                                                                                                                                                                                                                             title: { color: '#FF6B00', fontSize: 24, fontWeight: 'bold', textAlign: 'center', marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                               chat: { flex: 1, paddingHorizontal: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                 hint: { color: '#888', textAlign: 'center', marginTop: 100, fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                   msg: { padding: 12, marginVertical: 6, borderRadius: 16, maxWidth: '80%' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                     user: { backgroundColor: '#FF6B00', alignSelf: 'flex-end' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                       ai: { backgroundColor: '#222', alignSelf: 'flex-start', borderWidth: 1, borderColor: '#333' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                         msgText: { color: '#fff', fontSize: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                           inputRow: { flexDirection: 'row', padding: 12, gap: 8, borderTopWidth: 1, borderTopColor: '#222' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                             input: { flex: 1, backgroundColor: '#111', color: '#fff', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 10, maxHeight: 100 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                               btn: { backgroundColor: '#FF6B00', borderRadius: 20, paddingHorizontal: 20, justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 btnText: { color: '#000', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });